### ISSUE TITLE
When passwords don't match, the error is: Please match the requested format

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#152]
**Steps to reproduce**
1. Go to /signup
2. When asked to confirm password, enter wrong password in confirm password input.
3. Click create account

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64427789-4e6c7e80-d0b2-11e9-81c8-8925df944bf8.png)

**Comment by EpokK** [comment]
We are using [pattern HTML attribute](https://www.w3schools.com/tags/att_input_pattern.asp) to detect this particular case. It has a lot of advantages because it's controlled by the browser itself and [well supported](https://caniuse.com/#search=pattern). 

But we don't control this error message. If it becomes really critical for the user we can do the checking in Javascript but we highly recommend to not use that here.

**Comment by matstaz** [comment]
Just spoke with Richard and we will implement red design with message saying "passwords do not match"
