### ISSUE TITLE
[Safari] Reveal password part of the field is bigger than the field

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#240]
This can be found on all fields with Reveal password.

<img width="679" alt="Screenshot 2019-09-13 at 13 49 53" src="https://user-images.githubusercontent.com/54268246/64857658-d2cc7d80-d62d-11e9-9067-39951555399a.png">

**Comment by RandomAdversary** [comment]
This is also happening on mobile devices.

**Comment by nico3333fr** [comment]
Desing system is also impacted, Safari I love you 🥇

**Comment by nico3333fr** [comment]
Okay, this is fixed by several commits (live-debugging on design system 🎉 ) https://github.com/ProtonMail/design-system/commit/513807b2254a1ea92a7a5f48a05c0ef4cad4344f and https://github.com/ProtonMail/design-system/commit/9cf7c9249bccf553037395caf0742168079090a6


My iPad had the bug, it is fixed now. 
![Image d’iOS](https://user-images.githubusercontent.com/2578321/64872955-6ad76080-d648-11e9-9fbc-f0d55484122e.png)
