### ISSUE TITLE
"Thank you for your subscription" modal shows features which are not available to the user

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#55]
**Steps to reproduce**
1. Login with free account.
2. Upgrade ProtonVPN to paid plan.
3. Notice the features listed in Thank you for your subscription modal.

**Screenshot**
The account in the screenshot is free ProtonMail account and paid vpn account. This means the account doesn't have access to autoreply, custom domains and other features listed in the modal.
![image](https://user-images.githubusercontent.com/11393457/63429632-e3b51500-c41a-11e9-8e5f-1dec79740866.png)

**Comment by RandomAdversary** [comment]
Closing because I can't reproduce it multiple times. Will reopen if it happens again.

**Comment by gytiskin** [comment]
This modal from the screenshot can be seen when upgrading to Visionary plan. Reopening the issue.

Also, the bottom part of the modal seems irrelevant overall. It gives confusing information to the user. This is the modal when updating from Free to Basic:

<img width="836" alt="Screenshot 2019-08-22 at 13 31 42" src="https://user-images.githubusercontent.com/54268246/63507815-45d84d80-c4e1-11e9-9684-55bb5b5e5932.png">

**Comment by RandomAdversary** [comment]
We could add some of the vpn features in the modal. Ex: Use secure core, use premium servers, etc...

**Comment by matstaz** [comment]
@RandomAdversary 's this is tricky because secure core is only available for Plus and Visionary. if user selects basic VPN, he does not have it, nor P2P, nor video streaming.

If user subscribes to paid Mail only, show the standard (because we want to promote Free VPN)
If user subscribes to both, show the standard (logical)
If user subscribes to VPN only, we could do the following:

**Thank you!

Thank you for your subscription.
Your new features are now available.

Got it!

iOS logo [Download], Android logo [Download], Mac logo [Download], Windows logo [Download], Linux logo [Download]**

we use the same links as located here: https://protonvpn.com/download/#dl-clients

what do you say @EpokK ?

**Comment by EpokK** [comment]
I think we are adding complexity and unscallable solution (Drive? Calendar?). We should just remove this `footer`.

**Comment by matstaz** [comment]
yes @EpokK ! good call
