### ISSUE TITLE
Missing option to activate a ProtonMail mailbox

### ISSUE THREAD

**Issue by ZoranStojanovski** [ProtonMail/proton-vpn-settings#86]
If the user is logged-in with an account which does not have a ProtonMail mailbox, in the old design the user can click on the "Not activated" link in the Dashboard which redirects him to https://mail.protonmail.com/login in order to activate the mailbox. That's done by just entering the same credentials.

![pmredirect](https://user-images.githubusercontent.com/26218807/63951714-89e9c600-ca7e-11e9-9d43-189f676a54ae.PNG)

This function is missing in the new design. I think that the appropriate category in the new design would be the Account category, under the Username tab

**Comment by matstaz** [comment]
is there actually value is showing this to the user? We know if the user happens to log in to ProtonMail, he would have to go through the activation process to have the key generated.

@EpokK we can check this tomorrow. I would like to see if it can fit somewhere in ProtonVPN. Maybe in the dashboard because that's where subscription details are provided.

**Comment by jovanjovanovski** [comment]
We already have a `Username` section under `Account` in the new settings. We can add a second line here that says `ProtonMail address` that shows the users address, or simply `Not activated` that would link to the proton mail login page:

no PM address active
<img width="1288" alt="Screen Shot 2019-09-04 at 23 43 20" src="https://user-images.githubusercontent.com/16116122/64293942-fa588180-cf6d-11e9-9576-e8affe01c940.png">

PM address activated
<img width="1288" alt="Screen Shot 2019-09-04 at 23 44 04" src="https://user-images.githubusercontent.com/16116122/64293988-16f4b980-cf6e-11e9-8fd1-b1627bab700d.png">
