### ISSUE TITLE
(Suggestion) Remove the blue bar in the Dashboard for ProtonVPN Basic and Plus users

### ISSUE THREAD

**Issue by protonkeni** [ProtonMail/proton-vpn-settings#90]
As ProtonVPN Basic and Plus users are unable to assign their connections, the blue bar next to the number of VPN connections available serves no purpose and looks confusing so I think it's not necessary.

Example of what a Basic user sees:

![image (1)](https://user-images.githubusercontent.com/54706300/64015957-fc61b100-cb25-11e9-856c-508c7afe64d6.png)

Examples for what a Visionary user sees:

![image](https://user-images.githubusercontent.com/54706300/64015958-fc61b100-cb25-11e9-93f4-5d05f3b8073c.png)

![image](https://user-images.githubusercontent.com/54706300/64016054-42b71000-cb26-11e9-92b0-c58afd3c653b.png)

**Comment by B09B1** [comment]
Yes, I agree with this suggestion

**Comment by EpokK** [comment]
This subscription panel is used also in ProtonMail. It has been designed to display the number of VPN connections assigned and available for this account. Removing it makes the UI inconsistent with other add-ons (email, storage, VPN, domain, ...). I recommend to keep it because it's useful for people having an organization. If you really want to remove the progress bar, it will be remove for all.

**Comment by EpokK** [comment]
I removed the duplication of the row for `VPN connections`.
We need to keep progress bar as mentioned above. @matstaz if you want to update the subscription panel, feel free to provide a wireframe.
